#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DsCheques.UIClassic.Android.Resource", IsApplication=true)]

namespace DsCheques.UIClassic.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int activityIndicatorProgressBar = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int chequeImageView = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int emailText = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int loginButton = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int nameTextView = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int passwordText = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int priceTextView = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int productsListView = 2130837511;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int ChequeRow = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ChequesPage = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int LoginPage = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int ic_launcher = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ic_launcher_foreground = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ic_launcher_round = 2130968578;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int action_settings = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int login = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
